### ISSUE TITLE
Does not zoom to County when county summary is choosen

### ISSUE THREAD

**Issue by vwolfley** [AZMAG/map-ReadOnAZ#16]

**Comment by Jfairfield1** [comment]
Fixed County Summary zooming issue.  Was passing "Maricopa".  Needed to pass "Maricopa County".  I just added " County" to the name used in the where clause of the query.  Here is the relevant line:
`whereClause = readOnConfig.countySummary.summaryField + " = '" + self.communityName + " County'";`
