### ISSUE TITLE
Add key for users to know what performance levels mean

### ISSUE THREAD

**Issue by vwolfley** [AZMAG/map-ReadOnAZ#20]
Performance Leve 1= Minimally Proficient
Performance Level 2= Partially Proficient 
Performance Level 3= Proficient 
Performance Level 4= Highly Proficient

**Comment by Jfairfield1** [comment]
This looks like it is already done.  In the AZMERIT Breakdown tab, the chart legend looks like this:

![image](https://cloud.githubusercontent.com/assets/13153086/16463594/4e83b1f2-3deb-11e6-8357-965b3cc12108.png)

**Comment by vwolfley** [comment]
Sorry I think I forgot to close this one!
