### ISSUE TITLE
Match score colors in AzMERIT Scatter to dot colors on map

### ISSUE THREAD

**Issue by vwolfley** [AZMAG/map-ReadOnAZ#27]

**Comment by Jfairfield1** [comment]
Got it.

Changed 
`var sortOrder = [
                        "#d62d20",
                        "#ffa700",
                        "#9e379f",
                        "#0057e7",
                        "#028900"
                    ];`

to 
`var sortOrder = [
                        "red",
                        "orange",
                        "yellow",
                        "green",
                        "lime"
                    ];`

Seemed to do the trick.
