### ISSUE TITLE
In Schools Summary Report tab change letter grade to ELA score

### ISSUE THREAD

**Issue by vwolfley** [AZMAG/map-ReadOnAZ#38]

**Comment by Jfairfield1** [comment]
Is this what is supposed to change?  The badge in the top corner of the window?

![image](https://cloud.githubusercontent.com/assets/13153086/16463481/e1f1f68e-3dea-11e6-839c-aa4de0913db9.png)

**Comment by vwolfley** [comment]
![capture](https://cloud.githubusercontent.com/assets/5183539/16463558/280a0d5a-3deb-11e6-83e1-fae280032547.PNG)

No it is the letter grades in this column.

**Comment by Jfairfield1** [comment]
ahh...  Gotcha.  Thanks.
